'^/wp-admin$':
  to: "/wp/wp-admin/"
  regexp: true
'^/wp-admin/(.*)':
  to: "/wp/wp-admin/$1"
  regexp: true
'^(?!/wp/)(?!/wp-content/)(?!/wp-json/)(?!/wp-sitemap-.*.xml)(?!/wp-sitemap.xsl)(?!/wp-login.php)/(.+)$':
  to: "https://maintenance-09-12-2025.colby-museum-frontend.pages.dev/$1"
  regexp: true
